import 'package:flutter/material.dart';

/// A field explanation generated by AI.
class FieldExplanation {
  const FieldExplanation({
    required this.fieldName,
    required this.fieldValue,
    required this.explanation,
    this.context,
    this.tags = const [],
    this.relatedFields = const [],
    this.confidence = 1.0,
  });

  final String fieldName;
  final String fieldValue;
  final String explanation;
  final String? context;
  final List<String> tags;
  final List<String> relatedFields;
  final double confidence;
}

/// Types of explanation styles.
enum ExplanationStyle {
  /// Brief, one-sentence explanation
  brief,

  /// Detailed explanation with context
  detailed,

  /// Technical/expert-level explanation
  technical,

  /// Beginner-friendly explanation
  beginner,
}

/// Abstract interface for AI explanation service.
abstract class AIExplanationService {
  /// Generate an explanation for a specific field.
  Future<FieldExplanation> explainField({
    required String fieldName,
    required String fieldValue,
    String? propertyContext,
    ExplanationStyle style = ExplanationStyle.detailed,
  });

  /// Generate explanations for multiple fields.
  Future<List<FieldExplanation>> explainFields({
    required Map<String, String> fields,
    String? propertyContext,
    ExplanationStyle style = ExplanationStyle.detailed,
  });

  /// Get explanation for a term or concept.
  Future<String> explainTerm(String term);

  /// Check if the service is available.
  Future<bool> isAvailable();
}

/// Stub implementation for development.
class StubAIExplanationService implements AIExplanationService {
  static const _explanations = <String, String>{
    'FVI Score':
        'Fair Value Index (FVI) measures the potential profit margin on a tax lien property, considering market value, owed taxes, and redemption probability.',
    'Assessed Value':
        'The value assigned by the county tax assessor for taxation purposes. Often lower than market value.',
    'Tax Owed':
        'Total unpaid property taxes including penalties and interest that must be paid to redeem the property.',
    'Redemption Period':
        'The time window during which the original owner can reclaim their property by paying all owed taxes plus interest.',
    'Lien Position':
        'Priority ranking of the tax lien relative to other claims. First position liens are paid first in foreclosure.',
    'Interest Rate':
        'The statutory rate of return on your investment if the owner redeems the property.',
  };

  @override
  Future<FieldExplanation> explainField({
    required String fieldName,
    required String fieldValue,
    String? propertyContext,
    ExplanationStyle style = ExplanationStyle.detailed,
  }) async {
    // Simulate network delay
    await Future.delayed(const Duration(milliseconds: 500));

    final explanation = _explanations[fieldName] ??
        'This field shows the $fieldName for this property.';

    return FieldExplanation(
      fieldName: fieldName,
      fieldValue: fieldValue,
      explanation: explanation,
      context: propertyContext,
      tags: _getTagsForField(fieldName),
    );
  }

  @override
  Future<List<FieldExplanation>> explainFields({
    required Map<String, String> fields,
    String? propertyContext,
    ExplanationStyle style = ExplanationStyle.detailed,
  }) async {
    final results = <FieldExplanation>[];
    for (final entry in fields.entries) {
      results.add(await explainField(
        fieldName: entry.key,
        fieldValue: entry.value,
        propertyContext: propertyContext,
        style: style,
      ));
    }
    return results;
  }

  @override
  Future<String> explainTerm(String term) async {
    await Future.delayed(const Duration(milliseconds: 300));
    return _explanations[term] ?? 'No explanation available for "$term".';
  }

  @override
  Future<bool> isAvailable() async => true;

  List<String> _getTagsForField(String fieldName) {
    final lowerName = fieldName.toLowerCase();
    if (lowerName.contains('value') || lowerName.contains('price')) {
      return ['financial', 'valuation'];
    }
    if (lowerName.contains('tax') || lowerName.contains('lien')) {
      return ['tax', 'legal'];
    }
    if (lowerName.contains('owner') || lowerName.contains('deed')) {
      return ['ownership', 'title'];
    }
    return ['general'];
  }
}

/// State for the AI loupe overlay.
class AILoupeState {
  const AILoupeState({
    this.isActive = false,
    this.position = Offset.zero,
    this.targetField,
    this.explanation,
    this.isLoading = false,
    this.error,
  });

  final bool isActive;
  final Offset position;
  final String? targetField;
  final FieldExplanation? explanation;
  final bool isLoading;
  final String? error;

  AILoupeState copyWith({
    bool? isActive,
    Offset? position,
    String? targetField,
    FieldExplanation? explanation,
    bool? isLoading,
    String? error,
  }) {
    return AILoupeState(
      isActive: isActive ?? this.isActive,
      position: position ?? this.position,
      targetField: targetField ?? this.targetField,
      explanation: explanation ?? this.explanation,
      isLoading: isLoading ?? this.isLoading,
      error: error ?? this.error,
    );
  }
}
